name = "ECAEstimator"
uuid = "a8d96a81-0b46-4335-936c-3f4cf645bcc3"
authors = ["Gianna Marschmann"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
